import type {
	IRAttribute,
	IRAttributeGroup,
	IRGroup,
	IRObject,
	IRObjectField,
	IRSchema,
	IRType,
} from '../ir';
import { PATTERNS } from './patterns';
import {
	attrGroupIdent,
	groupIdent,
	indent,
	jsString,
	safeIdent,
	typeIdent,
} from './shared';

export interface SourceEmitOptions {
	exportName?: string;
}

interface SourceContext {
	schema: IRSchema;
	emittedTypes: Set<string>;
	emittedGroups: Set<string>;
	emittedAttrGroups: Set<string>;
}

export function emitZodSource(schema: IRSchema, opts: SourceEmitOptions = {}): string {
	const ctx: SourceContext = {
		schema,
		emittedTypes: new Set(),
		emittedGroups: new Set(),
		emittedAttrGroups: new Set(),
	};
	const isLibrary = !schema.rootName;
	const exportName = opts.exportName ?? (schema.rootName ? safeIdent(schema.rootName) : '');

	const lines: string[] = [];
	lines.push('/**');
	lines.push(' * AUTO-GENERATED by xsd2zod. Do not edit by hand.');
	if (isLibrary) {
		lines.push(' * Library schema (no root element) — exports named types only.');
	} else {
		lines.push(` * Source root element: ${schema.rootName}`);
	}
	if (schema.targetNamespace) {
		lines.push(` * Target namespace: ${schema.targetNamespace}`);
	}
	lines.push(' */');
	lines.push('');
	lines.push("import { z } from 'zod';");
	lines.push('');

	for (const [name, ag] of Object.entries(schema.attributeGroups)) {
		lines.push(emitAttributeGroup(name, ag, ctx));
		lines.push('');
	}

	for (const [name, group] of Object.entries(schema.groups)) {
		lines.push(emitGroup(name, group, ctx));
		lines.push('');
	}

	for (const [name, t] of Object.entries(schema.types)) {
		if (schema.groups[name]) continue;
		lines.push(emitNamedType(name, t, ctx));
		lines.push('');
	}

	if (!isLibrary && exportName) {
		// When `<xs:element name="Foo" type="Foo"/>` the type was already exported
		// under that name — re-emitting `export const Foo = z.lazy(() => Foo)` would
		// produce a duplicate identifier and a self-referential init-cycle.
		const rootSharesNameWithType =
			schema.rootName !== undefined &&
			schema.types[schema.rootName] !== undefined &&
			typeIdent(schema.rootName) === exportName;
		if (!rootSharesNameWithType) {
			lines.push(`export const ${exportName} = z.lazy(() => ${emitType(schema.root, ctx)});`);
			lines.push('');
		}
		lines.push(`export type ${exportName}Input = z.input<typeof ${exportName}>;`);
		lines.push(`export type ${exportName}Output = z.output<typeof ${exportName}>;`);
		lines.push('');
	}

	return lines.join('\n');
}

// Every named type / group emits as `z.lazy(() => …)` so the generated file
// is order-independent and supports cyclic references.
function emitNamedType(name: string, t: IRType, ctx: SourceContext): string {
	ctx.emittedTypes.add(name);
	return `export const ${typeIdent(name)} = z.lazy(() => ${emitType(t, ctx)});`;
}

function emitGroup(name: string, group: IRGroup, ctx: SourceContext): string {
	ctx.emittedGroups.add(name);
	return `export const ${groupIdent(name)} = z.lazy(() => ${emitType(group.type, ctx)});`;
}

function emitAttributeGroup(
	name: string,
	ag: IRAttributeGroup,
	ctx: SourceContext,
): string {
	ctx.emittedAttrGroups.add(name);
	const fields = ag.attributes.map((a) => emitAttributeField(a, ctx)).filter(Boolean);
	const body = fields.length
		? `z.object({\n${fields.map((f) => indent(f, 1)).join('\n')}\n})`
		: 'z.object({})';
	return `export const ${attrGroupIdent(name)} = z.lazy(() => ${body});`;
}

export function emitType(t: IRType, ctx: SourceContext): string {
	switch (t.kind) {
		case 'string':
			return emitString(t);
		case 'number':
			return emitNumber(t);
		case 'boolean':
			return appendDescribe('z.boolean()', t.doc);
		case 'date':
			return appendDescribe('z.iso.date()', t.doc);
		case 'dateTime':
			return appendDescribe('z.iso.datetime()', t.doc);
		case 'time':
			return appendDescribe('z.iso.time()', t.doc);
		case 'duration':
			return appendDescribe(regexExpr(PATTERNS.duration, 'z.string()'), t.doc);
		case 'gYear':
			return appendDescribe(regexExpr(PATTERNS.gYear, 'z.string()'), t.doc);
		case 'gYearMonth':
			return appendDescribe(regexExpr(PATTERNS.gYearMonth, 'z.string()'), t.doc);
		case 'gMonthDay':
			return appendDescribe(regexExpr(PATTERNS.gMonthDay, 'z.string()'), t.doc);
		case 'gMonth':
			return appendDescribe(regexExpr(PATTERNS.gMonth, 'z.string()'), t.doc);
		case 'gDay':
			return appendDescribe(regexExpr(PATTERNS.gDay, 'z.string()'), t.doc);
		case 'binary':
			return emitBinary(t);
		case 'anyURI':
			return emitAnyURI(t);
		case 'qname':
			return appendDescribe('z.string()', t.doc);
		case 'any':
			// xs:any processContents="skip" → z.any() (opt-out of validation).
			// "lax"/"strict" → z.unknown() (no runtime element registry to dispatch).
			return appendDescribe(
				t.processContents === 'skip' ? 'z.any()' : 'z.unknown()',
				t.doc,
			);
		case 'enum':
			return emitEnum(t);
		case 'object':
			return emitObject(t, ctx);
		case 'array':
			return emitArray(t, ctx);
		case 'list':
			return emitList(t, ctx);
		case 'union':
			return emitUnion(t, ctx);
		case 'ref':
			return emitRef(t);
	}
}

function emitString(t: Extract<IRType, { kind: 'string' }>): string {
	let s = 'z.string()';
	const min = t.length ?? t.minLength;
	const max = t.length ?? t.maxLength;
	if (min !== undefined && min > 0) s += `.min(${min})`;
	if (max !== undefined) s += `.max(${max})`;
	for (const p of t.patterns ?? []) s += `.regex(new RegExp(${jsString(p)}))`;
	return appendDescribe(s, t.doc);
}

function emitNumber(t: Extract<IRType, { kind: 'number' }>): string {
	let s = 'z.number()';
	if (t.integer) s += '.int()';
	if (t.min !== undefined) s += t.minExclusive ? `.gt(${t.min})` : `.min(${t.min})`;
	if (t.max !== undefined) s += t.maxExclusive ? `.lt(${t.max})` : `.max(${t.max})`;
	if (t.fractionDigits !== undefined && t.fractionDigits >= 0) {
		s += `.multipleOf(${Math.pow(10, -t.fractionDigits)})`;
	}
	return appendDescribe(s, t.doc);
}

function regexExpr(pattern: string, base: string): string {
	return `${base}.regex(new RegExp(${jsString(pattern)}))`;
}

function emitBinary(t: Extract<IRType, { kind: 'binary' }>): string {
	let s =
		t.encoding === 'hex'
			? regexExpr(PATTERNS.hexBinary, 'z.string()')
			: 'z.string().base64()';
	const min = t.length ?? t.minLength;
	const max = t.length ?? t.maxLength;
	if (min !== undefined && min > 0) s += `.min(${min})`;
	if (max !== undefined) s += `.max(${max})`;
	return appendDescribe(s, t.doc);
}

function emitAnyURI(t: Extract<IRType, { kind: 'anyURI' }>): string {
	let s = 'z.string()';
	const min = t.length ?? t.minLength;
	const max = t.length ?? t.maxLength;
	if (min !== undefined && min > 0) s += `.min(${min})`;
	if (max !== undefined) s += `.max(${max})`;
	for (const p of t.patterns ?? []) s += `.regex(new RegExp(${jsString(p)}))`;
	return appendDescribe(s, t.doc);
}

function emitEnum(t: Extract<IRType, { kind: 'enum' }>): string {
	const values = t.values.map((v) => jsString(v.value)).join(', ');
	const documentedValues = t.values.filter((value) => value.doc !== undefined);
	const valueDocs = documentedValues
		.map((value) => `${jsString(value.value)}: ${jsString(value.doc ?? '')}`)
		.join(', ');
	const metadata = valueDocs ? `.meta({ valueDocs: { ${valueDocs} } })` : '';
	return appendDescribe(`z.enum([${values}])${metadata}`, t.doc);
}

function emitObject(t: IRObject, ctx: SourceContext): string {
	const fieldLines = t.fields.map((f) => emitField(f, ctx));
	const attrLines = (t.attributes ?? []).map((a) => emitAttributeField(a, ctx));
	const allLines = [...attrLines, ...fieldLines];

	let body =
		allLines.length === 0
			? 'z.object({})'
			: `z.object({\n${allLines.map((l) => indent(l, 1)).join('\n')}\n})`;

	// xs:any → object accepts arbitrary extra keys via .passthrough().
	if (t.anys && t.anys.length > 0) {
		body = `${body}.passthrough()`;
	}

	// xs:complexContent + xs:extension → z.intersection(base, ownFields).
	if (t.extends && t.extends.kind === 'extension') {
		body = `z.intersection(${typeIdent(t.extends.baseRef)}, ${body})`;
	}

	// xs:choice inside xs:sequence → intersect with parent.
	for (const choiceField of t.choices ?? []) {
		body = `z.intersection(${body}, ${emitType(choiceField.type, ctx)})`;
	}

	// xs:group ref → intersect with the group's exported constant.
	for (const groupField of t.groupRefs ?? []) {
		if (groupField.type.kind === 'ref') {
			body = `z.intersection(${body}, ${groupIdent(groupField.type.name)})`;
		}
	}

	return appendDescribe(body, t.doc);
}

function emitField(field: IRObjectField, ctx: SourceContext): string {
	let inner = emitType(field.type, ctx);
	// xs:nillable → z.union([T, z.null()]).
	if (field.nillable) inner = `z.union([${inner}, z.null()])`;
	if (field.default !== undefined) inner = `${inner}.default(${jsString(field.default)})`;
	if (!field.required) inner = `${inner}.optional()`;
	return `${jsString(field.name)}: ${inner},`;
}

function emitAttributeField(a: IRAttribute, ctx: SourceContext): string {
	if (a.type.kind === 'ref' && a.type.refKind === 'attributeGroup') {
		return `// (attributeGroup ${a.name} merged via intersection)`;
	}
	let inner = emitType(a.type, ctx);
	if (a.fixed !== undefined) inner = `z.literal(${jsString(a.fixed)})`;
	if (a.default !== undefined) inner = `${inner}.default(${jsString(a.default)})`;
	if (a.use !== 'required') inner = `${inner}.optional()`;
	// XSD attributes → keys prefixed with `@` to avoid collision with elements.
	const key = jsString(`@${a.name}`);
	return `${key}: ${inner},`;
}

function emitArray(t: Extract<IRType, { kind: 'array' }>, ctx: SourceContext): string {
	let s = `z.array(${emitType(t.item, ctx)})`;
	if (typeof t.minOccurs === 'number' && t.minOccurs > 0) s += `.min(${t.minOccurs})`;
	if (typeof t.maxOccurs === 'number') s += `.max(${t.maxOccurs})`;
	return appendDescribe(s, t.doc);
}

function emitList(t: Extract<IRType, { kind: 'list' }>, ctx: SourceContext): string {
	let arrayExpr = `z.array(${emitType(t.item, ctx)})`;
	if (t.length !== undefined) arrayExpr += `.length(${t.length})`;
	else {
		if (t.minLength !== undefined) arrayExpr += `.min(${t.minLength})`;
		if (t.maxLength !== undefined) arrayExpr += `.max(${t.maxLength})`;
	}
	// xs:list lexical form: space-separated string → array.
	const wrapped = `z.preprocess((v) => typeof v === 'string' ? v.trim().split(/\\s+/) : v, ${arrayExpr})`;
	return appendDescribe(wrapped, t.doc);
}

function emitUnion(t: Extract<IRType, { kind: 'union' }>, ctx: SourceContext): string {
	if (t.variants.length === 0) return appendDescribe('z.never()', t.doc);
	if (t.variants.length === 1) {
		const v = t.variants[0];
		return v ? appendDescribe(emitType(v, ctx), t.doc) : 'z.never()';
	}
	const variants = t.variants.map((v) => emitType(v, ctx)).join(', ');
	return appendDescribe(`z.union([${variants}])`, t.doc);
}

function emitRef(t: Extract<IRType, { kind: 'ref' }>): string {
	switch (t.refKind) {
		case 'group':
			return appendDescribe(groupIdent(t.name), t.doc);
		case 'attributeGroup':
			return appendDescribe(attrGroupIdent(t.name), t.doc);
		case 'element':
		case 'type':
		default:
			return appendDescribe(typeIdent(t.name), t.doc);
	}
}

function appendDescribe(expr: string, doc: string | undefined): string {
	return doc ? `${expr}.describe(${jsString(doc)})` : expr;
}
